Plugins/Plugin.Shipping.ByWeight/Controllers/ShippingByWeightController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Urs.Data.Domain.Directory;
using Urs.Plugin.Shipping.ByWeight.Domain;
using Urs.Plugin.Shipping.ByWeight.Models;
using Urs.Plugin.Shipping.ByWeight.Services;
using Urs.Services.Configuration;
using Urs.Services.Directory;
using Urs.Services.Localization;
using Urs.Services.Security;
using Urs.Services.Shipping;
using Urs.Framework;
using Urs.Framework.Controllers;
using Urs.Framework.Kendoui;
using Urs.Framework.Mvc;
using Urs.Framework.Mvc.Filters;

namespace Urs.Plugin.Shipping.ByWeight.Controllers
{
    [AdminAuthorize]
    [Area("Admin")]
    public class ShippingByWeightController : BasePluginController
    {
        private readonly IShippingService _shippingService;
        private readonly ShippingByWeightSettings _shippingByWeightSettings;
        private readonly IShippingByWeightService _shippingByWeightService;
        private readonly ISettingService _settingService;
        private readonly ILocalizationService _localizationService;
        private readonly IAreaService _areaService;

        public ShippingByWeightController(IShippingService shippingService,
            ShippingByWeightSettings shippingByWeightSettings,
            IShippingByWeightService shippingByWeightService, ISettingService settingService,
            ILocalizationService localizationService,
            IAreaService areaService)
        {
            this._shippingService = shippingService;
            this._shippingByWeightSettings = shippingByWeightSettings;
            this._shippingByWeightService = shippingByWeightService;
            this._settingService = settingService;
            this._localizationService = localizationService;
            this._areaService = areaService;
        }

        #region Methods

        public ActionResult Configure()
        {
            return View("~/Plugins/Shipping.ByWeight/Views/Configure.cshtml");
        }

        public IActionResult RatesList(PageRequest command)
        {
            var records = _shippingByWeightService.GetAll(command.Page - 1, command.Limit);
            var sbwModel = records.Select(x =>
            {
                var m = new ShippingByWeightModel()
                {
                    Id = x.Id,
                    ShippingMethodId = x.ShippingMethodId,
                    First = x.First,
                    Plus = x.Plus,
                    FirstPrice = x.FirstPrice,
                    PlusPrice = x.PlusPrice
                };

                if (x.Scopes.Count > 0)
                {
                    var areas = new List<string>();
                    var provinceCodes = x.Scopes.Select(s => s.ProvinceCode).Distinct().ToList();

                    foreach (var pCode in provinceCodes)
                    {
                        var province = _areaService.GetProvincesByCode().FirstOrDefault(q => q.Code == pCode);
                        var cities = _areaService.GetCitiesByProvinceCode(province.Code);
                        var count = cities.Count();
                        var scope = x.Scopes.Where(s => s.ProvinceCode == pCode);
                        var scopeCount = scope.Count();
                        if (count != scopeCount)
                            foreach (var s in scope)
                            {
                                var city = cities.FirstOrDefault(c => c.Code == s.CityCode);
                                areas.Add(city.Name);
                            }
                        else
                            areas.Add(province.Name);
                    }
                    m.AreasName = string.Join(",", areas);
                }
                else
                    m.AreasName = _localizationService.GetResource("Plugins.Shipping.ByPiece.Fields.Default");


                var shippingMethod = _shippingService.GetShippingMethodById(x.ShippingMethodId);
                m.ShippingMethodName = (shippingMethod != null) ? shippingMethod.Name : "Unavailable";

                return m;
            }).ToList();
            var model = new ResponseResult
            {
                data = sbwModel,
                count = records.TotalCount
            };

            return Json(model);
        }

        public ActionResult RateDelete(int id)
        {
            var sbw = _shippingByWeightService.GetById(id);
            if (sbw != null)
                _shippingByWeightService.DeleteShippingByWeightRecord(sbw);

            return new NullJsonResult();
        }

        #region item

        //edit
        public ActionResult EditPopup(int? id)
        {
            var model = new ShippingByWeightModel();
            var sbw = new ShippingByWeightRecord();
            if (id.HasValue)
            {
                sbw = _shippingByWeightService.GetById(id.Value);
                model.Id = sbw.Id;
                model.Plus = sbw.Plus;
                model.PlusPrice = sbw.PlusPrice;
                model.ShippingMethodId = sbw.ShippingMethodId;
                model.First = sbw.First;
                model.FirstPrice = sbw.FirstPrice;
            }

            var provinces = _areaService.GetProvincesByCode(); ;

            var provinceCodes = sbw.Scopes.Select(s => s.ProvinceCode).Distinct().ToList();

            foreach (var province in provinces)
            {
                var cities = _areaService.GetCitiesByProvinceCode(province.Code);
                var count = cities.Count();
                var scope = sbw.Scopes.Where(s => s.ProvinceCode == province.Code);
                var scopeCount = scope.Count();
                var selected = false;
                if (count == scopeCount)
                    selected = true;

                var editShipping = new EditShippingScopeModel();
                editShipping.Code = province.Code;
                editShipping.Name = province.Name;
                editShipping.Selected = selected;
                editShipping.Count = scopeCount;

                foreach (var item in cities)
                {
                    var c = sbw.Scopes.FirstOrDefault(x => x.ProvinceCode == province.Code && x.CityCode == item.Code);
                    var cselected = false;
                    if (c != null)
                    {
                        cselected = true;
                        editShipping.Disabled = true;
                    }

                    var city = new EditShippingScopeModel.ShippingCityModel();
                    city.Code = item.Code;
                    city.Name = item.Name;
                    city.Selected = cselected;

                    editShipping.Cities.Add(city);
                }
                model.Scopes.Add(editShipping);
            }

            var shippingMethods = _shippingService.GetAllShippingMethods();
            if (!shippingMethods.Any())
                return Content("No shipping methods can be loaded");

            var selectedShippingMethod = _shippingService.GetShippingMethodById(sbw.ShippingMethodId);
            //shipping methods
            foreach (var sm in shippingMethods)
                model.AvailableShippingMethods.Add(new SelectListItem { Text = sm.Name, Value = sm.Id.ToString(), Selected = (selectedShippingMethod != null && sm.Id == selectedShippingMethod.Id) });

            return View("~/Plugins/Shipping.ByWeight/Views/EditPopup.cshtml", model);
        }

        [HttpPost]
        public ActionResult EditPopup(ShippingByWeightModel model)
        {
            var entity = _shippingByWeightService.GetById(model.Id);
            if (entity == null)
            {
                entity = new ShippingByWeightRecord();
                entity.Plus = model.Plus;
                entity.PlusPrice = model.PlusPrice;
                entity.ShippingMethodId = model.ShippingMethodId;
                entity.First = model.First;
                entity.FirstPrice = model.FirstPrice;
                _shippingByWeightService.InsertShippingByWeightRecord(entity);
            }
            else
            {
                entity.Plus = model.Plus;
                entity.PlusPrice = model.PlusPrice;
                entity.ShippingMethodId = model.ShippingMethodId;
                entity.First = model.First;
                entity.FirstPrice = model.FirstPrice;
                _shippingByWeightService.UpdateShippingByWeightRecord(entity);
            }

            if (model.City != null && model.City.Count() > 0)
            {
                var scopes = _shippingByWeightService.GetScopesByPieceRecordId(entity.Id);
                foreach (var item in scopes)
                    _shippingByWeightService.DeleteShippingScope(item);

                foreach (var cityCode in model.City)
                {
                    var city = _areaService.GetCityByCityCode(cityCode);
                    var sbw = new ShippingScopeByWeightRecord()
                    {
                        ShippingByWeightRecordId = entity.Id,
                        ProvinceCode = city.ProvinceCode,
                        CityCode = city.CityCode
                    };
                    _shippingByWeightService.InsertShippingScope(sbw);
                }
            }

            return Json(new { success = 1 });
        }

        #endregion

        #endregion
    }
}

Plugins/Plugin.Shipping.ByWeight/Views/Configure.cshtml
@{
    Layout = "_LayuiAdminLayout";
}
@using Urs.Plugin.Shipping.ByWeight.Models;
@using Urs.Framework;
@using Urs.Core.Infrastructure;

<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <button class="layui-btn layuiadmin-btn-tags" data-type="add">添加</button>
                </div>
            </div>
        </div>
        <div class="layui-card-body">
            <p>
                <b>
                    @T("Plugins.Shipping.ByWeight.Formula")
                </b>
                @T("Plugins.Shipping.ByWeight.Formula.Value")
            </p>
            <table id="LAY-resource-list" lay-data="" lay-filter="LAY-resource-list"></table>
            <script type="text/html" id="layuiadmin-app-cont-tagsbar">
                <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="layui-icon layui-icon-edit"></i>编辑</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del"><i class="layui-icon layui-icon-delete"></i>删除</a>
            </script>
        </div>
    </div>
</div>

<script>
    layui.config({
        base: '../../../layuiadmin/' //静态资源所在路径
    }).extend({
        index: 'lib/index' //主入口模块
    }).use(['index','table','form'], function () {
        var table = layui.table
            ,form = layui.form;
        //分类管理
        table.render({
            elem: '#LAY-resource-list'
            , method: 'post'
            , id:'resource-list'
            , url: '@Html.Raw(Url.Action("RatesList", "ShippingByWeight"))' //模拟接口
            , page: true //开启分页
            , even: true
            , limit: 30
            , limits: [15, 30, 50, 100]
            , cols: [[
                { type: 'numbers', fixed: 'left' }
                , { field: 'AreasName', title: '@T("Plugins.Shipping.ByWeight.Fields.AreasName")', minWidth: 250 }
                , { field: 'ShippingMethodName', title: '@T("Plugins.Shipping.ByWeight.Fields.ShippingMethod")',  width: 100 }
                , { field: 'First', title: '@T("Plugins.Shipping.ByWeight.Fields.First")', width: 100 }
                , { field: 'FirstPrice', title: '@T("Plugins.Shipping.ByWeight.Fields.FirstPrice")', width: 100 }
                , { field: 'Plus', title: '@T("Plugins.Shipping.ByWeight.Fields.Plus")', width: 100 }
                , { field: 'PlusPrice', title: '@T("Plugins.Shipping.ByWeight.Fields.PlusPrice")', width: 100 }
                , { title: '操作', width: 220, align: 'center', fixed: 'right', toolbar: '#layuiadmin-app-cont-tagsbar' }
            ]]
            , text: { none: '一条数据也没有^_^' }
        });

        //监听工具条
        table.on('tool(LAY-resource-list)', function (obj) {
            var data = obj.data;
            if (obj.event === 'del') {
                layer.confirm('确定删除？', function (index) {
                    obj.del();
                    $.post('@Html.Raw(Url.Action("RateDelete", "ShippingByWeight"))', { id: obj.data.Id });
                    layer.close(index);
                });
            } else if (obj.event === 'edit') {
                layer.open({
                    type: 2
                    , title: '编辑'
                    , content: '@Url.Action("EditPopup", "ShippingByWeight")?id=' + data.Id
                    , area: ['800px', '600px']
                    , btn: ['确定', '取消']
                    , yes: function (index, layero) {
                        //点击确认触发 iframe 内容中的按钮提交
                        var submit = layero.find('iframe').contents().find("#layuiadmin-app-form-submit");
                        submit.click();
                    }
                });
            }
        });
        var $ = layui.$, active = {
            add: function () {
                layer.open({
                    type: 2
                    , title: '编辑'
                    , content: '@Url.Action("EditPopup", "ShippingByWeight")'
                    , area: ['800px', '600px']
                    , btn: ['确定', '取消']
                    , yes: function (index, layero) {
                        //点击确认触发 iframe 内容中的按钮提交
                        var submit = layero.find('iframe').contents().find("#layuiadmin-app-form-submit");
                        submit.click();
                    }
                });
            }
        }
        $('.layui-btn.layuiadmin-btn-tags').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
    });
</script>

Plugins/Plugin.Shipping.ByWeight/Views/EditPopup.cshtml
@{
    Layout = "_LayuiAdminLayout";
}
<script src="~/admin/scripts/jquery-1.7.1.js"></script>
@using Urs.Plugin.Shipping.ByWeight.Models;
@using Urs.Framework.TagHelpers.Admin
@using Urs.Framework;
@using Urs.Core.Infrastructure;
@model ShippingByWeightModel
<style>
    .dcity {
        vertical-align: middle;
        display: block;
        overflow: hidden;
        z-index: 1;
    }

    .ecity {
        position: relative;
        float: left;
        margin-right: 1px;
        padding-right: 8px;
        height: 30px;
        width: 90px;
    }

    .dialog-areas span.gareas {
        white-space: nowrap;
        margin-right: 3px;
        padding: 4px 4px 1px;
        display: inline-block;
        position: relative;
        height: 17px;
        border: 1px solid #fff;
    }

    .dialog-areas .citys span.areas {
        margin-right: 3px;
        padding: 4px 0 1px 4px;
        display: inline-block;
    }

    .dialog-areas input, .dialog-areas button {
        vertical-align: middle;
    }

    .check_num {
        color: #F60;
        font-size: 12px;
        letter-spacing: -1px;
    }

    .trigger {
        width: 8px;
        height: 8px;
        padding: 2px;
        cursor: pointer;
    }

    .dialog-areas label {
        margin: 0 1px;
    }

    .dialog-areas .btns {
        padding: 5px 0 5px 10px;
        margin-left: 330px;
        clear: both;
    }

    .showCityPop {
        z-index: 55556;
    }

        .showCityPop .citys {
            display: block;
            z-index: 55900;
        }

    .dialog-areas .showCityPop .gareas {
        background-color: #FFFEC6;
        border: solid 1px #f7e4a5;
        border-bottom: solid 1px #FFFEC6;
        z-index: 56000;
    }

    .citys {
        background-color: #FFFEC6;
        position: absolute;
        float: right;
        border: solid 1px #f7e4a5;
        z-index: 20000;
        top: 23px;
        left: 0;
        width: 214px;
        display: none;
    }

    .pictures_upload img {
        vertical-align: middle;
        padding: 5px;
    }
</style>


<div class="layui-col-md12">
    <div class="layui-card">
        <div class="layui-card-header">区域</div>
        <div class="layui-card-body">
            <div class="dialog-areas">
                <div class="dcity clearfix">
                    <div class="province-list">
                        @Html.HiddenFor(model => model.Id)
                        @foreach (var item in Model.Scopes)
                        {
                            <div class="ecity">
                                <span class="gareas">
                                    <input type="checkbox" value="310000" class="Province" @(item.Disabled ? "disabled " : string.Empty) @(item.Selected ? "checked" : string.Empty)>
                                    <label>@item.Name</label>
                                    <span class="check_num">@(item.Count != 0 ? "(" + item.Count + ")" : "")</span>
                                    <img class="trigger" src="/images/ico-city.gif" />
                                </span>
                                <div class="citys">
                                    @foreach (var city in item.Cities)
                                    {
                                        <span class="areas">
                                            <input type="checkbox" value="@city.Code" name="City" class="City" @(city.Selected ? "checked" : string.Empty)>
                                            <label>@city.Name</label>
                                        </span>
                                    }
                                    <p style="text-align: right; margin: 0;">
                                        <input type="button" value="关闭" class="close_button">
                                    </p>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="layui-card">
        <div class="layui-card-header">运费</div>
        <div class="layui-card-body">
            <div class="layui-form" lay-filter="">
                <div class="layui-form-item">
                    <nop-label asp-for="ShippingMethodId" />
                    <div class="layui-input-inline">
                        <input asp-for="Id" type="hidden" />
                        <nop-select asp-for="ShippingMethodId" asp-items="Model.AvailableShippingMethods" />
                        <span asp-validation-for="ShippingMethodId"></span>
                    </div>
                </div>
                <div class="layui-row layui-col-space10 layui-form-item">
                    <div class="layui-col-sm6">
                        <nop-label asp-for="First" />
                        <div class="layui-input-block">
                            <nop-editor asp-for="First" />
                            <span asp-validation-for="First"></span>
                        </div>
                    </div>
                    <div class="layui-col-sm6">
                        <nop-label asp-for="FirstPrice" />
                        <div class="layui-input-block">
                            <nop-editor asp-for="FirstPrice" />
                            <span asp-validation-for="FirstPrice"></span>
                        </div>
                    </div>
                </div>
                <div class="layui-row layui-col-space10 layui-form-item">
                    <div class="layui-col-sm6">
                        <nop-label asp-for="Plus" />
                        <div class="layui-input-block">
                            <nop-editor asp-for="Plus" />
                            <span asp-validation-for="Plus"></span>
                        </div>
                    </div>
                    <div class="layui-col-sm6">
                        <nop-label asp-for="PlusPrice" />
                        <div class="layui-input-block">
                            <nop-editor asp-for="PlusPrice" />
                            <span asp-validation-for="PlusPrice"></span>
                        </div>
                    </div>
                </div>
                <div class="layui-form-item" style="display:none;">
                    <div class="layui-input-block">
                        <button id="layuiadmin-app-form-submit" class="layui-btn" lay-submit lay-filter="btn_save">确认保存</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var citiesArray = [];
    $(function () {
        $('.trigger').click(function () {
            var gareas = $(this).parent().parent();
            if (gareas.hasClass("showCityPop")) {
                gareas.removeClass("showCityPop");
            } else {
                $(".ecity").removeClass("showCityPop");
                gareas.addClass("showCityPop");
            }
        });
        $('.close_button').click(function () {
            $(".ecity").removeClass("showCityPop");
        });
        $('.City').click(function () {
            var value = $(this).attr("checked");
            var checknum = $(this).parent().parent().parent().find(".check_num");
            var numStr = checknum.html();
            var num = 0;
            if (numStr != null && numStr != "") {
                num = numStr.substr(1, numStr.length - 2);
            }
            num = parseInt(num);
            if (value != undefined && value == "checked") {
                citiesArray.push($(this).val());
                num = num + 1;
            } else if (num > 1) {
                var pos = $.inArray($(this).val(), citiesArray);
                citiesArray.splice(pos, 1);
                num = num - 1;
            }
            checknum.html("(" + num + ")");
        });
        $('.Province').click(function () {
            var value = $(this).attr("checked");
            var gareas = $(this).parent().parent();
            var cities = gareas.find('.City');
            cities.each(function () {
                if (value != undefined && value == "checked") {
                    $(this).attr("checked", true);
                    citiesArray.push($(this).val());
                    var count = cities.length;
                    gareas.find(".check_num").html("(" + count + ")");
                } else {
                    var pos = $.inArray($(this).val(), citiesArray);
                    citiesArray.splice(pos, 1);
                    $(this).attr("checked", false);
                    gareas.find(".check_num").html("");
                }
            });
        });
    });
</script>

<script>
    layui.config({
        base: '../../../layuiadmin/' //静态资源所在路径
    }).extend({
        index: 'lib/index' //主入口模块
    }).use(['index', 'set'], function () {
        var $ = layui.$
            , form = layui.form
            ,active = { }
        form.on('submit(btn_save)', function (obj) {
            var index = layer.load(2, { shade: false });
            var field = obj.field; //获取提交的字段
            field.City = citiesArray;
            //layer.msg(JSON.stringify(obj.field));
            //提交 Ajax 成功后，关闭当前弹层并重载表格
            $.post('@Url.Action("EditPopup")', field, function (rep) {
                layer.close(index);
                layer.msg("保存成功,即将自动关闭", { time: 2 * 1000 }, function () {
                    var iframe_index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
                    console.log("当前iframe层的索引:" + iframe_index + "==window.name:" + window.name);
                    parent.layer.close(iframe_index); //再执行关闭
                    window.parent.location.reload();
                });
            });
            return false;
         });
        $('.layui-btn.layuiadmin-btn-tags').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });

    });
</script>