Urs.Shop/Areas/Admin/Controllers/PictureController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Urs.Core.Infrastructure;
using Urs.Services.Media;
using Urs.Services.Security;
using Urs.Framework.Controllers;

namespace Urs.Admin.Controllers
{
    [AdminAuthorize]
    public partial class PictureController : BaseAdminController
    {
        private readonly IPictureService _pictureService;
        private readonly IUrsFileProvider _fileProvider;
        private readonly IPermissionService _permissionService;

        public PictureController(IPictureService pictureService,
            IUrsFileProvider fileProvider,
             IPermissionService permissionService)
        {
            this._pictureService = pictureService;
            this._fileProvider = fileProvider;
            this._permissionService = permissionService;
        }

        [HttpPost]
        public IActionResult AsyncUpload()
        {
            var httpPostedFile = Request.Form.Files.FirstOrDefault();
            if (httpPostedFile == null)
            {
                return Json(new
                {
                    success = false,
                    message = "No file uploaded",
                    downloadGuid = Guid.Empty
                });
            }
            var fileBinary = GetDownloadBits(httpPostedFile);

            const string qqFileNameParameter = "qqfilename";
            var fileName = httpPostedFile.FileName;
            if (string.IsNullOrEmpty(fileName) && Request.Form.ContainsKey(qqFileNameParameter))
                fileName = Request.Form[qqFileNameParameter].ToString();
            //remove path (passed in IE)
            fileName = _fileProvider.GetFileName(fileName);

            var contentType = httpPostedFile.ContentType;

            var fileExtension = _fileProvider.GetFileExtension(fileName);
            if (!string.IsNullOrEmpty(fileExtension))
                fileExtension = fileExtension.ToLowerInvariant();

            if (String.IsNullOrEmpty(contentType))
            {
                switch (fileExtension)
                {
                    case ".bmp":
                        contentType = "image/bmp";
                        break;
                    case ".gif":
                        contentType = "image/gif";
                        break;
                    case ".jpeg":
                    case ".jpg":
                    case ".jpe":
                    case ".jfif":
                    case ".pjpeg":
                    case ".pjp":
                        contentType = "image/jpeg";
                        break;
                    case ".png":
                        contentType = "image/png";
                        break;
                    case ".tiff":
                    case ".tif":
                        contentType = "image/tiff";
                        break;
                    default:
                        break;
                }
            }

            var picture = _pictureService.InsertPicture(fileBinary, contentType, null, true);
            return Json(new { success = true, pictureId = picture.Id,
                imageUrl = _pictureService.GetPictureUrl(picture, 100) });
        }

        public virtual byte[] GetDownloadBits(IFormFile file)
        {
            using (var fileStream = file.OpenReadStream())
            {
                using (var ms = new MemoryStream())
                {
                    fileStream.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    return fileBytes;
                }
            }
        }
    }
}

Urs.Shop/Controllers/CommonController.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Urs.Core;
using Urs.Data.Domain.Configuration;
using Urs.Services.Directory;
using Urs.Services.Logging;

namespace Urs.Web.Controllers
{
    public partial class CommonController : Controller
    {
        #region Fields

        private readonly IWebHelper _webHelper;
        private readonly CommonSettings _commonSettings;
        private readonly IAreaService _areaService;
        private readonly IWorkContext _workContext;
        private readonly ILogger _logger;

        #endregion

        #region Constructors

        public CommonController(IWebHelper webHelper,
            CommonSettings commonSettings,
            IAreaService areaService,
            IWorkContext workContext,
            ILogger logger)
        {
            this._webHelper = webHelper;
            this._commonSettings = commonSettings;
            this._areaService = areaService;
            this._workContext = workContext;
            this._logger = logger;
        }

        #endregion

        #region Methods

        //page not found
        public virtual IActionResult PageNotFound()
        {
            if (_commonSettings.Log404Errors)
            {
                var statusCodeReExecuteFeature = HttpContext?.Features?.Get<IStatusCodeReExecuteFeature>();
                //TODO add locale resource
                _logger.Error($"Error 404. The requested page ({statusCodeReExecuteFeature?.OriginalPath}) was not found",
                    user: _workContext.CurrentUser);
            }

            Response.StatusCode = 404;
            Response.ContentType = "text/html";

            return View();
        }

        public IActionResult Config()
        {
            return View();
        }

        //footer

        public IActionResult JavaScriptDisabledWarning()
        {
            if (!_commonSettings.DisplayJavaScriptDisabledWarning)
                return Content("");

            return PartialView();
        }
        //store is closed
        public IActionResult StoreClosed()
        {
            return View();
        }

        public JsonResult ProvincesSelector(string selectedValue)
        {
            var list = _areaService.GetProvinces();

            return Json(new SelectList(list, selectedValue));
        }

        public JsonResult CitiesSelector(string provincename)
        {
            var list = _areaService.GetCities(provincename);
            return Json(new SelectList(list));
        }

        public JsonResult AreasSelector(string provincename, string cityname)
        {
            var list = _areaService.GetAreas(provincename, cityname)
                ;
            return Json(new SelectList(list));
        }
        #endregion
    }
}

Urs.Shop/Controllers/UEditorController.cs
using Microsoft.AspNetCore.Mvc;
using UEditorNetCore;

namespace Urs.Web.Controllers
{
    //do not inherit it from BasePublicController. otherwise a lot of extra action filters will be called
    //they can create guest account(s), etc
    public partial class UEditorController : Controller
    {
        private UEditorService ue;
        public UEditorController(UEditorService ue)
        {
            this.ue = ue;
        }
        public void Do()
        {
            ue.DoAction(HttpContext);
        }
    }
}

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/Address.cshtml
@model AddressModel
<input asp-for="Id" type="hidden" />
<input asp-for="NameEnabled" type="hidden" />
<input asp-for="NameRequired" type="hidden" />
<input asp-for="CompanyEnabled" type="hidden" />
<input asp-for="CompanyRequired" type="hidden" />
<input asp-for="ProvincesEnabled" type="hidden" />
<input asp-for="LatitudeEnabled" type="hidden" />
<input asp-for="LongitudeEnabled" type="hidden" />
<input asp-for="StreetAddressEnabled" type="hidden" />
<input asp-for="StreetAddressRequired" type="hidden" />
<input asp-for="StreetAddress2Enabled" type="hidden" />
<input asp-for="StreetAddress2Required" type="hidden" />
<input asp-for="ZipPostalCodeEnabled" type="hidden" />
<input asp-for="ZipPostalCodeRequired" type="hidden" />
<input asp-for="PhoneEnabled" type="hidden" />
<input asp-for="PhoneRequired" type="hidden" />
<input asp-for="FaxEnabled" type="hidden" />
<input asp-for="FaxRequired" type="hidden" />

@if (Model.NameEnabled)
{
    <div class="layui-form-item">
        <u-label asp-for="Name" />
        <div class="layui-input-inline">
            <u-editor asp-for="Name" />
            <span asp-validation-for="Name"></span>
        </div>
    </div>
}
@if (Model.CompanyEnabled)
{
    <div class="layui-form-item">
        <u-label asp-for="Company" />
        <div class="layui-input-inline">
            <u-editor asp-for="Company" />
            <span asp-validation-for="Company"></span>
        </div>
    </div>
}
@if (Model.ProvincesEnabled)
{
    <div class="layui-form-item">
        <u-label asp-for="ProvinceName" />
        <div class="layui-input-inline">
            <u-select asp-for="ProvinceName" data-value="@Html.Raw(Model.ProvinceName)" />
        </div>
    </div>
    <div class="layui-form-item">
        <u-label asp-for="CityName" data-value="@Html.Raw(Model.CityName)" />
        <div class="layui-input-inline">
            <u-select asp-for="CityName" />
        </div>
    </div>
    <div class="layui-form-item">
        <u-label asp-for="AreaName" data-value="@Html.Raw(Model.AreaName)" />
        <div class="layui-input-inline">
            <u-select asp-for="AreaName" />
        </div>
    </div>
}
@if (Model.StreetAddressEnabled)
{
    <div class="layui-form-item">
        <u-label asp-for="Address1" />
        <div class="layui-input-inline">
            <u-editor asp-for="Address1" />
            <span asp-validation-for="Address1"></span>
        </div>
    </div>
}
@if (Model.StreetAddress2Enabled)
{
    <div class="layui-form-item">
        <u-label asp-for="Address2" />
        <div class="layui-input-inline">
            <u-editor asp-for="Address2" />
            <span asp-validation-for="Address2"></span>
        </div>
    </div>
}
@if (Model.LatitudeEnabled && Model.LongitudeEnabled)
{
    <div class="layui-form-item">
        <u-label asp-for="Latitude" />
        <div class="layui-input-inline">
            <u-editor asp-for="Latitude" />
            <span asp-validation-for="Latitude"></span>
        </div>
    </div>
    <div class="layui-form-item">
        <u-label asp-for="Longitude" />
        <div class="layui-input-inline">
            <u-editor asp-for="Longitude" />
            <span asp-validation-for="Longitude"></span>
        </div>
    </div>
}
@if (Model.ZipPostalCodeEnabled)
{
    <div class="layui-form-item">
        <u-label asp-for="ZipPostalCode" />
        <div class="layui-input-inline">
            <u-editor asp-for="ZipPostalCode" />
            <span asp-validation-for="ZipPostalCode"></span>
        </div>
    </div>
}
@if (Model.PhoneEnabled)
{
    <div class="layui-form-item">
        <u-label asp-for="PhoneNumber" />
        <div class="layui-input-inline">
            <u-editor asp-for="PhoneNumber" />
            <span asp-validation-for="PhoneNumber"></span>
        </div>
    </div>
}
@if (Model.FaxEnabled)
{
    <div class="layui-form-item">
        <u-label asp-for="FaxNumber" />
        <div class="layui-input-inline">
            <u-editor asp-for="FaxNumber" />
            <span asp-validation-for="FaxNumber"></span>
        </div>
    </div>
}
<script type="text/javascript">
    layui.use(['index'], function () {
        var $ = layui.$;

        var ddlProvince = $("#@Html.IdFor(model => model.ProvinceName)");
        var ddlCity = $("#@Html.IdFor(model => model.CityName)");
        var ddlArea = $("#@Html.IdFor(model => model.AreaName)");
        ddlProvince.change(function () {
            var provinceId = $(this).val()||$(this).data("value");
            SelectCity(provinceId);
        });
        ddlCity.change(function () {
            var cityId = $(this).val() || $(this).data("value");;
            SelectArea(cityId);
        });

        var provinceId = ddlProvince.val() || ddlProvince.data("value");;
        SelectProvince(provinceId);

        function SelectProvince(provinceId) {
            var isChild = false;
            $.ajax({
                cache: false,
                type: "GET",
                url: "@(Url.Action("ProvincesSelector", "Common"))",
                data: { "selectedValue": provinceId },
                success: function (data) {
                    ddlProvince.html('');
                    ddlProvince.append($('<option></option>').val("").html("—请选择—"));
                    $.each(data, function (id, option) {
                        if (option.Selected) { isChild = true; }
                        ddlProvince.append($('<option></option>').val(option.Value).attr("selected", option.Selected).html(option.Text));
                    });
                },
                complete: function (obj) {
                    if (obj.status == 200) {
                        var dataStr = obj.responseText;
                        var data = eval("(" + dataStr + ")");
                        if ((data instanceof Array) && data.length > 0) {
                            var provinceId = isChild ? ddlProvince.val() : data[0].Value;
                            SelectCity(provinceId);

                        }
                    }
                }
            });
        }

        function SelectCity(provinceId) {
            var isChild = false;
            var cityId = ddlCity.val() || ddlCity.data("value");
            $.ajax({
                cache: false,
                type: "GET",
                url: "@(Url.Action("CitiesSelector", "Common"))",
                data: { "provincename": provinceId },
                success: function (data) {
                    ddlCity.html('');
                    ddlCity.append($('<option></option>').val("").html("—请选择—"));
                    $.each(data, function (id, option) {
                        if (option.Value == cityId) { isChild = true; }
                        ddlCity.append($('<option></option>').val(option.Value).attr("selected", option.Value == cityId ? true : false).html(option.Text));
                    });

                },
                complete: function (obj) {
                    if (obj.status == 200) {
                        var dataStr = obj.responseText;
                        var data = eval("(" + dataStr + ")");
                        if ((data instanceof Array) && data.length > 0) {
                            var cityId = isChild ? ddlCity.val() : data[0].Value;
                            SelectArea(cityId, provinceId);
                        }
                    }
                }
            });
        }

        function SelectArea(cityId, provinceId) {
            var areaId = ddlArea.val() || ddlArea.data("value");
            $.ajax({
                cache: false,
                type: "GET",
                url: "@(Url.Action("AreasSelector", "Common"))",
                data: { "cityname": cityId, "provincename": provinceId },
                success: function (data) {
                    ddlArea.css({ display: "none" });
                    ddlArea.html('');
                    ddlArea.append($('<option></option>').val("").html("—请选择—"));
                    $.each(data, function (id, option) {
                        ddlArea.append($('<option></option>').val(option.Value).attr("selected", option.Value == areaId ? true : false).html(option.Text));
                    });
                    if (ddlArea.html() != "") {
                        ddlArea.css({ display: "block" });
                    }
                }
            });
        }

    });
</script>

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/Date.cshtml
@model DateTime
<input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@((Model > DateTime.MinValue ? Model : DateTime.Today).ToShortDateString())" />

 <script>
layui.use('laydate', function(){
  var laydate = layui.laydate;
  //执行一个laydate实例
  laydate.render({
    elem: '#@Html.IdForModel()' //指定元素
  });
});
 </script>

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/DateNullable.cshtml
@model DateTime?
<input type="text" name="@Html.NameForModel()" id="@Html.IdForModel()" value="@(Model > DateTime.MinValue || Model.HasValue ? Model.Value.ToShortDateString() : null)" lay-verify="date" placeholder="yyyy-MM-dd" autocomplete="off" class="layui-input">

<script>
layui.use('laydate', function(){
  var laydate = layui.laydate;
  //执行一个laydate实例
  laydate.render({
    elem: '#@Html.IdForModel()' //指定元素
  });
});
</script>

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime
@using System.Globalization
<input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@((Model > DateTime.MinValue ? Model : DateTime.Today).ToString(CultureInfo.CurrentCulture.DateTimeFormat))" />

<script>
layui.use('laydate', function(){
  var laydate = layui.laydate;
  //执行一个laydate实例
  laydate.render({
    elem: '#@Html.IdForModel()' //指定元素
  });
});
</script>

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/DateTimeNullable.cshtml
@model DateTime?
@using System.Globalization
 <input type="text" name="@Html.NameForModel()" id="@Html.IdForModel()" value="@((Model > DateTime.MinValue || Model.HasValue) ? Model.Value.ToString(CultureInfo.CurrentCulture.DateTimeFormat) : null)"  placeholder="yyyy-MM-dd"  class="layui-input">

 <script>
layui.use('laydate', function(){
  var laydate = layui.laydate;
  //执行一个laydate实例
  laydate.render({
    elem: '#@Html.IdForModel()' //指定元素
  });
});
 </script>

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/Decimal.cshtml
@model Decimal
<input asp-for="@Model" asp-format="{0:F2}"  class="layui-input" />
@{
    var postfix = "";
    if (ViewData.ContainsKey("postfix") && ViewData["postfix"] != null)
    {
        postfix = ViewData["postfix"].ToString();
    }
}@postfix

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/DecimalNullable.cshtml
@model Decimal?
<input asp-for="@Model" asp-format="{0:F2}" class="layui-input" />
@{
    var postfix = "";
    if (ViewData.ContainsKey("postfix") && ViewData["postfix"] != null)
    {
        postfix = ViewData["postfix"].ToString();
    }
}@postfix

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/Double.cshtml
@model Double
<input asp-for="@Model" class="layui-input" />
@{
    var postfix = "";
    if (ViewData.ContainsKey("postfix") && ViewData["postfix"] != null)
    {
        postfix = ViewData["postfix"].ToString();
    }
}

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/Int32.cshtml
@model Int32


<input asp-for="@Model" class="layui-input" />
@{
    var postfix = "";
    if (ViewData.ContainsKey("postfix") && ViewData["postfix"] != null)
    {
        postfix = ViewData["postfix"].ToString();
    }
}@postfix

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/Int32Nullable.cshtml
@model Int32?
<input asp-for="@Model" class="layui-input" />
@{
    var postfix = "";
    if (ViewData.ContainsKey("postfix") && ViewData["postfix"] != null)
    {
        postfix = ViewData["postfix"].ToString();
    }
}
@postfix

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/MultiSelect.cshtml
@model List<int>
<select asp-for="@Model" asp-items="@((IEnumerable<SelectListItem>)ViewData["SelectList"])" multiple="multiple" lay-filter="@Html.IdForModel()"></select>

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/Picture.cshtml
@model int
@inject IPictureService pictureService

@using Urs.Core;
@using Urs.Services.Media

@{
    const int pictureSize = 100;
    //other variables
    var random = CommonHelper.GenerateRandomInteger();
    var clientId = "picture" + random;
    var pictureUrl = pictureService.GetPictureUrl(Model,targetSize: pictureSize);
}
<div class="layui-upload">
    <button type="button" class="layui-btn" id="@clientId">上传图片</button>
    <div class="layui-upload-list" id="@(clientId + "value")">
        <img class="layui-upload-img" id="@(clientId)-picture" src="@pictureUrl">
        <input type="hidden" asp-for="@Model" />
        <p id="@(clientId)-msg"></p>
    </div>
</div>
<script>
    layui.use('upload', function () {
        var $ = layui.jquery
            , upload = layui.upload;
        //普通图片上传
        var uploadInst = upload.render({
            elem: '#@clientId'
            , url: '@(Url.Content("~/Admin/Picture/AsyncUpload"))'
            , before: function (obj) {
                //预读本地文件示例，不支持ie8
                obj.preview(function (index, file, result) {
                    $('#@(clientId)-picture').attr('src', '/icon/loading-lizi.gif'); //图片链接（base64）
                });
            }
            , done: function (res) {
                //如果上传失败
                if (res.error > 0) {
                    return layer.msg('上传失败');
                }
                if (res.success) {
                    $("#@(clientId + "-picture")").attr('src', res.imageUrl);
                    $("#@(clientId + "value") input").val(res.pictureId);
                }
                //上传成功
            }
            , error: function () {
                //演示失败状态，并实现重传
                var demoText = $('#@(clientId)-msg');
                demoText.html('<span style="color: #FF5722;">上传失败</span> <a class="layui-btn layui-btn-xs demo-reload">重试</a>');
                demoText.find('.demo-reload').on('click', function () {
                    uploadInst.upload();
                });
            }
        });
    });
</script>

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/Pictures.cshtml
@model String
@using Urs.Core;
@{
    //register CSS and JS
    //Html.AddCssFileParts("~/admin/content/fileuploader.css");
    //Html.AddScriptParts("~/admin/scripts/fileuploader.js");

    //other variables
    var random = CommonHelper.GenerateRandomInteger();
    var clientId = "picture" + random;
}
<div id="@(clientId + "value")">
    @Html.HiddenFor(x => x)
</div>
<div id="@(clientId + "image")" class="pictures_upload"></div>
<span id="@(clientId + "remove")" class="t-button" style="display:none;">@T("Admin.Picture.RemovePicture")</span>
<br />
<div id="@clientId"></div>
<script type="text/javascript">
    $(function () {
        $(function () {
            var image@(clientId)Value=new Array();

            var uploader@(clientId) = new qq.FileUploader({
                element: document.getElementById('@clientId'),
                action: '@(Url.Content("~/Admin/Picture/AsyncUpload"))',
                onComplete: function (id, fileName, responseJSON) {
                    if (responseJSON.success) {
                        $image = $("#@(clientId + "image")");
                        $values = $("#@(clientId + "value") input");
                        $image.html($image.html() + "<img src='" + responseJSON.imageUrl + "'/>");

                        image@(clientId)Value.push(responseJSON.pictureId);
                        var imageValues='';
                        for(var i=0;i<image@(clientId)Value.length;i++){
                            imageValues+=image@(clientId)Value[i]+",";
                        }
                        imageValues=imageValues.substring(0,imageValues.length-1);
                        $values.val(imageValues);
                        $("#@(clientId + "remove")").show();
                    }
                },
                strings: {
                    upload: "@T("Common.FileUploader.Upload")",
                    drop: "@T("Common.FileUploader.DropFiles")",
                    cancel: "@T("Common.FileUploader.Cancel")",
                    failed: "@T("Common.FileUploader.Failed")"
                }
            });

            $("#@(clientId + "remove")").click(function (e) {
                $("#@(clientId + "image")").html("");
                $("#@(clientId + "value") input").val("");
                $(this).hide();
            });
        });
    });
</script>

Urs.Shop/Areas/Admin/Views/Shared/EditorTemplates/SimpleUEditor.cshtml
@model String

<textarea asp-for="@Model">@ViewData.TemplateInfo.FormattedModelValue</textarea>
<!-- 配置文件 -->
<script type="text/javascript" src="~/admin/content/ueditor/ueditor-simple.config.js"></script>
<!-- 编辑器源码文件 -->
<script type="text/javascript" src="~/admin/content/ueditor/ueditor.all.js"></script>
<!-- 实例化编辑器 -->
<script type="text/javascript">
    var uesimple = UE.getEditor('@Html.IdForModel()', { initialFrameHeight: 300, autoHeightEnabled: true });
    uesimple.ready(function () {
        uesimple.setHeight(300);
    });
</script>