Urs.Shop/Areas/Admin/Models/Banners/BannerItemAddPopupModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Urs.Framework.Models;

namespace Urs.Admin.Models.Banners
{
    public partial class BannerItemAddPopupModel : BaseEntityModel
    {
        [DisplayName("标题")]
        public virtual string Title { get; set; }

        [DisplayName("副标题")]
        public virtual string SubTitle { get; set; }
        [DisplayName("链接")]
        public virtual string Url { get; set; }
        [DisplayName("图片")]
        [UIHint("Picture")]
        public int PictureId { get; set; }
        public int BannerSliderZoneId { get; set; }
        [DisplayName("排序")]
        public virtual int DisplayOrder { get; set; }
    }
}

Urs.Shop/Areas/Admin/Models/Banners/BannerItemModel.cs
using System.ComponentModel.DataAnnotations;
using Urs.Framework.Models;

namespace Urs.Admin.Models.Banners
{
    public partial class BannerItemModel : BaseEntityModel
    {
        public int BannerZoneId { get; set; }
        public virtual string Title { get; set; }
        public virtual string SubTitle { get; set; }
        public virtual string Url { get; set; }

        [UIHint("Picture")]
        public virtual int PictureId { get; set; }
        public virtual string PictureUrl { get; set; }

        public virtual int DisplayOrder { get; set; }
    }
}

Urs.Shop/Areas/Admin/Models/Banners/BannerListModel.cs
using Microsoft.AspNetCore.Mvc;
using Urs.Framework;
using Urs.Framework.Mvc;

using Urs.Framework.Kendoui;

namespace Urs.Admin.Models.Banners
{
    public partial class BannerListModel : BaseModel
    {
        [UrsDisplayName("Admin.Store.Banners.List.SearchBrandName")]
        
        public string SearchBannersName { get; set; }

        public ResponseResult Banners { get; set; }
    }
}

Urs.Shop/Areas/Admin/Models/Banners/BannerModel.cs
using System.ComponentModel;
using Urs.Framework.Models;
using Urs.Framework.Mvc;

namespace Urs.Admin.Models.Banners
{
    public partial class BannerModel : BaseEntityModel
    {
        [DisplayName("名称")]
        public virtual string Name { get; set; }
        [DisplayName("样式名称")]
        public virtual string ClassName { get; set; }
        [DisplayName("空间名称")]
        public virtual string ZoneName { get; set; }
        [DisplayName("模板名称(非必填)")]
        public virtual string TemplateName { get; set; }
    }
}

Urs.Shop/Areas/Admin/Controllers/BannerController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Urs.Admin.Models.Banners;
using Urs.Core;
using Urs.Data.Domain.Banners;
using Urs.Data.Domain.Configuration;
using Urs.Services.Banners;
using Urs.Services.Localization;
using Urs.Services.Logging;
using Urs.Services.Media;
using Urs.Services.Security;
using Urs.Framework.Controllers;
using Urs.Framework.Extensions;
using Urs.Framework.Kendoui;

namespace Urs.Admin.Controllers
{
    [AdminAuthorize]
    public partial class BannerController : BaseAdminController
    {
        #region Fields

        private readonly IBannerService _bannerService;
        private readonly IPictureService _pictureService;
        private readonly ILocalizationService _localizationService;
        private readonly IWorkContext _workContext;
        private readonly IActivityLogService _activityLogService;
        private readonly IPermissionService _permissionService;
        private readonly AdminAreaSettings _adminAreaSettings;

        #endregion

        #region Constructors
        public BannerController(
            IBannerService bannerService,
            IPictureService pictureService,
            ILocalizationService localizationService,
            IWorkContext workContext,
            IActivityLogService activityLogService,
            IPermissionService permissionService,
            AdminAreaSettings adminAreaSettings)
        {
            this._bannerService = bannerService;
            this._pictureService = pictureService;
            this._localizationService = localizationService;
            this._workContext = workContext;
            this._activityLogService = activityLogService;
            this._permissionService = permissionService;
            this._adminAreaSettings = adminAreaSettings;
        }

        #endregion

        #region List

        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBanner))
                return HttpUnauthorized();

            var model = new BannerListModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult List(PageRequest command, BannerListModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBanner))
                return HttpUnauthorized();

            var banner = _bannerService.GetAll(command.Page - 1, command.Limit);
            var result = new ResponseResult
            {
                data = banner.Select(x => x.ToModel<BannerModel>()),
                count = banner.TotalCount
            };
            return Json(result);
        }

        public IActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBanner))
                return HttpUnauthorized();

            var banner = _bannerService.GetById(id);
            if (banner == null)
            {
                var models = new BannerModel();
                return View(models);
            }
            var model = banner.ToModel<BannerModel>();
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(BannerModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBanner))
                return HttpUnauthorized();

            var banner = _bannerService.GetById(model.Id);
            if (banner == null)
            {
                var banners = model.ToEntity<Banner>();
                _bannerService.InsertBannerZone(banners);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    banner = model.ToEntity(banner);
                    _bannerService.UpdateBannerZone(banner);
                }
            }
            return Json(new { success = 1 });
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBanner))
                return HttpUnauthorized();

            var banner = _bannerService.GetById(id);
            if (banner == null)
                return Json(new { error = 1 });

            _bannerService.DeleteBannerZone(banner);
            return Json(new { success = 1 });
        }
        #endregion

        #region Goods spec

        public IActionResult Banner(int id)
        {
            ViewBag.BannerId = id;
            return View();
        }

        [HttpPost]
        public IActionResult BannerItem(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBanner))
                return HttpUnauthorized();

            var bannerItemList = _bannerService.GetItemsById(id);
            var bannerItemListModel = bannerItemList
                .Select(x =>
                {
                    var pvaModel = x.ToModel<BannerItemModel>();
                    pvaModel.PictureUrl = _pictureService.GetPictureUrl(x.PictureId, 200);
                    return pvaModel;
                })
                .ToList();

            var model = new ResponseResult
            {
                data = bannerItemListModel,
                count = bannerItemListModel.Count
            };
            return Json(model);
        }

        public IActionResult ItemUpdate(int id, int zoneId)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBanner))
                return HttpUnauthorized();

            var model = new BannerItemModel();
            var pva = _bannerService.GetBannerItemById(id);

            if (pva != null)
                model = pva.ToModel<BannerItemModel>();

            model.BannerZoneId = zoneId;
            return View(model);
        }

        [HttpPost]
        public IActionResult ItemUpdate(BannerItemModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBanner))
                return HttpUnauthorized();

            var pva = _bannerService.GetBannerItemById(model.Id);
            if (pva == null)
            {
                pva = new BannerItem();
                pva.Title = model.Title;
                pva.Url = model.Url;
                pva.BannerId = model.BannerZoneId;
                pva.SubTitle = model.SubTitle;
                pva.PictureId = model.PictureId;
                pva.DisplayOrder = model.DisplayOrder;
                _bannerService.InsertItem(pva);
            }
            else
            {
                pva.Title = model.Title;
                pva.Url = model.Url;
                pva.SubTitle = model.SubTitle;
                pva.PictureId = model.PictureId;
                pva.DisplayOrder = model.DisplayOrder;
                _bannerService.UpdateItem(pva);
            }
            return Json(new { success = 1 });
        }

        [HttpPost]
        public IActionResult ItemDelete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageBanner))
                return HttpUnauthorized();

            var pva = _bannerService.GetBannerItemById(id);
            if (pva == null)
                return Json(new { error = 1 });

            _bannerService.DeleteItem(pva);

            return Json(new { success = 1 });
        }

        #endregion


    }
}

Urs.Shop/Areas/Admin/Views/Banner/Banner.cshtml
@model BannerModel

<style type="text/css">
    .laytable-cell-1-PictureUrl {
        height: 100%;
        max-width: 100%;
    }
    .layui-table img {
        max-width: 160px;
    }
    .layui-table-view .layui-table td {
        padding: 0px;
    }
</style>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <button class="layui-btn layui-btn-normal layuiadmin-btn-tags" data-type="add">添加</button>
                </div>
            </div>
        </div>
        <div class="layui-card-body">
            <table id="LAY-banner-list" lay-data="" lay-filter="LAY-banner-list"></table>
            <script type="text/html" id="layuiadmin-app-cont-tagsbar">
                <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="layui-icon layui-icon-edit"></i>编辑</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del"><i class="layui-icon layui-icon-delete"></i>删除</a>
            </script>
        </div>
    </div>
</div>

<script>
    layui.use(['index','table','form'], function () {
        var table = layui.table
            ,form = layui.form;
        //分类管理
        table.render({
            elem: '#LAY-banner-list'
            , method: 'post'
            , id:'resource-list'
            , url: '@Html.Raw(Url.Action("BannerItem", "Banner",new { id=ViewBag.BannerId }))' //模拟接口
            , page: true //开启分页
            , even: true
            , limit: 30
            , limits: [15, 30, 50, 100]
            , cols: [[
                { type: 'numbers', fixed: 'left', style: 'height:130px;'  }
                , { field: 'PictureUrl', width: 160, style: 'height:120px;', title: '图片', templet: '<div><img height=120 src={{d.PictureUrl}}></div>' }
                , { field: 'Title', title: '标题', minWidth: 100, style: 'height:130px;'  }
                , { field: 'SubTitle', title: '副标题', minWidth: 100, style: 'height:130px;'  }
                , { field: 'DisplayOrder', title: '顺序', minWidth: 100, style: 'height:130px;'  }
                , { title: '操作', width: 220, align: 'center', fixed: 'right', toolbar: '#layuiadmin-app-cont-tagsbar', style: 'height:130px;'  }
            ]]
            , text: { none: '一条数据也没有^_^' }
        });

        //监听工具条
        table.on('tool(LAY-banner-list)', function (obj) {
            var data = obj.data;
            if (obj.event === 'del') {
                layer.confirm('确定删除？', function (index) {
                    obj.del();
                    $.post('@Url.Action("ItemDelete")', { id: obj.data.Id });
                    layer.close(index);
                });
            } else if (obj.event === 'edit') {
                layer.open({
                    type: 2
                    , title: '编辑'
                    , content: '@Url.Action("ItemUpdate")?id=' + data.Id + '&zoneId=' +@ViewBag.BannerId
                    , shade: 0.2
                    , maxmin: true
                    , shadeClose: true
                    , area: ['500px', '560px']
                    , btn: ['确定', '取消']
                    , yes: function (index, layero) {
                        
                        var submit = layero.find('iframe').contents().find("#set_system_submit_btn");
                        submit.click();
                    }
                });
            }
        });
        //监听单元格编辑
        table.on('edit(LAY-banner-list)', function (obj) {
            var value = obj.value //得到修改后的值
                , data = obj.data //得到所在行所有键值
                , field = obj.field; //得到字段
            $.post('@Url.Action("ItemUpdate")', { id: data.Id,name:obj.data.Name,value:obj.data.Value});
        });
        //监听搜索
        form.on('submit(LAY-app-contlist-search)', function (data) {
            var field = data.field;
            //执行重载
            table.reload('resource-list', {
                url:'@Html.Raw(Url.Action("List", "Banner"))'
                ,where: field
            });
        });
        var $ = layui.$, active = {
            add: function () {
                layer.open({
                    type: 2
                    , title: '编辑'
                    , content: '@Url.Action("ItemUpdate")?zoneId=@ViewBag.BannerId'
                    , shade: 0.2
                    , maxmin: true
                    , shadeClose: true
                    , area: ['600px', '400px']
                    , btn: ['确定', '取消']
                    , yes: function (index, layero) {
                        
                        var submit = layero.find('iframe').contents().find("#set_system_submit_btn");
                        submit.click();
                    }
                });
            }
        }
        $('.layui-btn.layuiadmin-btn-tags').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
    });
</script>

Urs.Shop/Areas/Admin/Views/Banner/Edit.cshtml
@model BannerModel
<div class="layui-col-md12">
    <div class="layui-card">
        <div class="layui-card-body">
            <div class="layui-form" wid200 lay-filter="">
                <input asp-for="Id" type="hidden" />
                <div class="layui-form-item">
                    <u-label asp-for="Name" />
                    <div class="layui-input-inline">
                        <u-editor asp-for="Name" />
                    </div>
                </div>
                <div class="layui-form-item">
                    <u-label asp-for="ClassName" />
                    <div class="layui-input-inline">
                        <u-editor asp-for="ClassName" />
                    </div>
                </div>
                <div class="layui-form-item">
                    <u-label asp-for="ZoneName" />
                    <div class="layui-input-inline">
                        <u-editor asp-for="ZoneName" />
                    </div>
                </div>
                <div class="layui-form-item">
                    <u-label asp-for="TemplateName" />
                    <div class="layui-input-inline">
                        <u-editor asp-for="TemplateName" />
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-input-block">
                        <button id="set_system_submit_btn" style="display:none" class="layui-btn" lay-submit lay-filter="set_system_submit_btn">确认保存</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    layui.use(['index'], function () {
        var $ = layui.$
            , form = layui.form
            ,active = { }
        form.on('submit(set_system_submit_btn)', function (obj) {
            var index = layer.load(2, { shade: false });
          var field = obj.field; //获取提交的字段
            //layer.msg(JSON.stringify(obj.field));
            //提交 Ajax 成功后，关闭当前弹层并重载表格
            $.post('@Url.Action("Edit")', field, function (rep) {
                layer.close(index);
                layer.msg("保存成功,即将自动关闭", { time: 2 * 1000 }, function () {
                    var iframe_index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
                    console.log("当前iframe层的索引:" + iframe_index + "==window.name:" + window.name);
                    parent.layer.close(iframe_index); //再执行关闭
                    window.parent.location.reload();
                });
            });
            
            return false;
    });
        $('.layui-btn.layuiadmin-btn-tags').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });

    });
</script>

Urs.Shop/Areas/Admin/Views/Banner/ItemUpdate.cshtml
@model BannerItemModel


<div class="layui-col-md12">
    <div class="layui-card">
        <div class="layui-card-body">
            <div class="layui-form" wid100 lay-filter="">
                <input asp-for="Id" type="hidden" />
                <input asp-for="BannerZoneId" type="hidden" />
                <div class="layui-form-item">
                    <label class="layui-form-label">标题</label>
                    <div class="layui-input-inline">
                        <u-editor asp-for="Title" />
                    </div>
                </div>
                <div class="layui-form-item" style="display:none;">
                    <label class="layui-form-label">简介</label>
                    <div class="layui-input-inline">
                        <u-editor asp-for="SubTitle" />
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">链接</label>
                    <div class="layui-input-inline">
                        <u-editor asp-for="Url" />
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">图片</label>
                    <div class="layui-input-inline">
                        <u-editor asp-for="PictureId" />
                    </div>
                </div>
                <div class="layui-form-item" style="display:none;">
                    <label class="layui-form-label">排序</label>
                    <div class="layui-input-inline">
                        <u-editor asp-for="DisplayOrder" />
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-input-block">
                        <button id="set_system_submit_btn" style="display:none" class="layui-btn" lay-submit lay-filter="set_system_submit_btn">确认保存</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    layui.use(['index'], function () {
        var $ = layui.$
            , form = layui.form;

        form.on('submit(set_system_submit_btn)', function (obj) {
            var index = layer.load(2, { shade: false });
              var field = obj.field; //获取提交的字段
                //提交 Ajax 成功后，关闭当前弹层并重载表格
                $.post('@Url.Action("ItemUpdate")', field, function (rep) {
                    if (rep.success == 1) {
                        layer.close(index);
                        layer.msg("保存成功,即将自动关闭", { time: 2 * 1000 }, function () {
                            var iframe_index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
                            console.log("当前iframe层的索引:" + iframe_index + "==window.name:" + window.name);
                            parent.layer.close(iframe_index); //再执行关闭
                            window.parent.location.reload();
                        });
                    }
                });
                return false;
        });
        $('.layui-btn.layuiadmin-btn-tags').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
    });

</script>

Urs.Shop/Areas/Admin/Views/Banner/List.cshtml
@model BannerListModel
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <button class="layui-btn  layui-btn-normal layuiadmin-btn-tags" data-type="add">添加</button>
                </div>
            </div>
        </div>
        <div class="layui-card-body">
            <table id="LAY-banner-list" lay-data="" lay-filter="LAY-banner-list"></table>
            <script type="text/html" id="layuiadmin-app-cont-tagsbar">
                <a class="layui-btn layui-btn-xs" lay-event="banner"><i class="layui-icon layui-icon-edit"></i>广告图</a>
                <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="layui-icon layui-icon-edit"></i>编辑</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del"><i class="layui-icon layui-icon-delete"></i>删除</a>
            </script>
        </div>
    </div>
</div>

<script>
    layui.use(['index','table','form'], function () {
        var table = layui.table
            ,form = layui.form;
        //分类管理
        table.render({
            elem: '#LAY-banner-list'
            , method: 'post'
            , id:'resource-list'
            , url: '@Html.Raw(Url.Action("List"))' //模拟接口
            , page: true //开启分页
            , even: true
            , limit: 30
            , limits: [15, 30, 50, 100]
            , cols: [[
                { type: 'numbers', fixed: 'left' }
                , { field: 'Name', title: '名称', minWidth: 100 }
                , { field: 'ZoneName', title: '空间名',  minWidth: 100 }
                , { field: 'TemplateName', title: '模板名称', minWidth: 100 }
                , { title: '操作', width: 220, align: 'center', fixed: 'right', toolbar: '#layuiadmin-app-cont-tagsbar' }
            ]]
            , text: { none: '一条数据也没有^_^' }
        });

        //监听工具条
        table.on('tool(LAY-banner-list)', function (obj) {
            var data = obj.data;
            if (obj.event === 'del') {
                layer.confirm('确定删除？', function (index) {
                    obj.del();
                    $.post('@Url.Action("Delete")', { id: obj.data.Id });
                    layer.close(index);
                });
            } else if (obj.event === 'edit') {
                layer.open({
                    type: 2
                    , title: '编辑'
                    , content: '@Url.Action("Edit")?id=' + data.Id
                    , shade: 0.2
                    , maxmin: true
                    , shadeClose: true
                    , area: ['600px', '400px']
                    , btn: ['确定', '取消']
                    , yes: function (index, layero) {
                        
                        var submit = layero.find('iframe').contents().find("#set_system_submit_btn");
                        submit.click();
                    }
                });
            } else if (obj.event == 'banner') {
                var index = layer.open({
                    title: '编辑'
                    , type: 2
                    , shade: 0.2
                    , maxmin: true
                    , shadeClose: true
                    , area: ['100%', '100%']
                    , content: '@Url.Action("Banner")?id=' + data.Id
                });
                $(window).on("resize", function () {
                    layer.full(index);
                });
                return false;
            }
        });
        //监听单元格编辑
        table.on('edit(LAY-banner-list)', function (obj) {
            var value = obj.value //得到修改后的值
                , data = obj.data //得到所在行所有键值
                , field = obj.field; //得到字段
            $.post('@Url.Action("Edit")', { id: data.Id,name:obj.data.Name,value:obj.data.Value});
        });
        //监听搜索
        form.on('submit(LAY-app-contlist-search)', function (data) {
            var field = data.field;
            //执行重载
            table.reload('resource-list', {
                url:'@Html.Raw(Url.Action("List", "Banner"))'
                ,where: field
            });
        });
        var $ = layui.$, active = {
            add: function () {
                layer.open({
                    type: 2
                    , title: '编辑'
                    , content: '@Url.Action("Edit")'
                    , shade: 0.2
                    , maxmin: true
                    , shadeClose: true
                    , area: ['600px', '400px']
                    , btn: ['确定', '取消']
                    , yes: function (index, layero) {
                        
                        var submit = layero.find('iframe').contents().find("#set_system_submit_btn");
                        submit.click();
                    }
                });
            }
        }
        $('.layui-btn.layuiadmin-btn-tags').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
    });
</script>


