Urs.Shop/Areas/Admin/Controllers/LogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using Urs.Admin.Models.Logging;
using Urs.Core;
using Urs.Data.Domain.Logging;
using Urs.Services;
using Urs.Services.Localization;
using Urs.Services.Logging;
using Urs.Services.Security;
using Urs.Framework.Controllers;
using Urs.Framework.Kendoui;

namespace Urs.Admin.Controllers
{
    [AdminAuthorize]
    public partial class LogController : BaseAdminController
    {
        private readonly ILogger _logger;
        private readonly IWorkContext _workContext;
        private readonly ILocalizationService _localizationService;

        private readonly IPermissionService _permissionService;

        public LogController(ILogger logger, IWorkContext workContext,
            ILocalizationService localizationService,
            IPermissionService permissionService)
        {
            this._logger = logger;
            this._workContext = workContext;
            this._localizationService = localizationService;

            this._permissionService = permissionService;
        }

        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSystemLog))
                return HttpUnauthorized();

            var model = new LogListModel();
            model.AvailableLogLevels = LogLevel.Debug.ToSelectList(false).ToList();
            model.AvailableLogLevels.Insert(0, new SelectListItem() { Text = _localizationService.GetResource("Admin.Common.All"), Value = "0" });

            return View(model);
        }

        [HttpPost]
        public IActionResult LogList(PageRequest command, LogListModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSystemLog))
                return HttpUnauthorized();

            DateTime? createdOnFromValue = (model.CreateTimeFrom == null) ? null
                            : (DateTime?)model.CreateTimeFrom.Value;

            DateTime? createdToFromValue = (model.CreateTimeTo == null) ? null
                            : (DateTime?)model.CreateTimeTo.Value.AddDays(1);

            LogLevel? logLevel = model.LogLevelId > 0 ? (LogLevel?)(model.LogLevelId) : null;


            var logItems = _logger.GetAllLogs(createdOnFromValue, createdToFromValue, model.Message,
                logLevel, command.Page - 1, command.Limit);
            var result = new ResponseResult
            {
                data = logItems.Select(x =>
                {
                    return new LogModel()
                    {
                        Id = x.Id,
                        LogLevel = x.LogLevel.GetLocalizedEnum(_localizationService),
                        ShortMessage = x.ShortMessage,
                        FullMessage = x.FullMessage,
                        IpAddress = x.IpAddress,
                        UserId = x.UserId,
                        UserEmail = x.User != null ? x.User.Email : null,
                        PageUrl = x.PageUrl,
                        ReferrerUrl = x.ReferrerUrl,
                        CreateTime = x.CreateTime
                    };
                }),
                count = logItems.TotalCount
            };
            return Json(result);
        }

        [HttpPost]
        public IActionResult ClearAll()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSystemLog))
                return HttpUnauthorized();

            _logger.ClearLog();

            return Json(new { success = 1 });
        }

        public IActionResult View(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSystemLog))
                return HttpUnauthorized();

            var log = _logger.GetLogById(id);
            if (log == null)
                //No log found with the specified id
                return RedirectToAction("List");

            var model = new LogModel()
            {
                Id = log.Id,
                LogLevel = log.LogLevel.GetLocalizedEnum(_localizationService),
                ShortMessage = log.ShortMessage,
                FullMessage = log.FullMessage,
                IpAddress = log.IpAddress,
                UserId = log.UserId,
                UserEmail = log.User != null ? log.User.Email : null,
                PageUrl = log.PageUrl,
                ReferrerUrl = log.ReferrerUrl,
                CreateTime = log.CreateTime
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSystemLog))
                return HttpUnauthorized();

            var log = _logger.GetLogById(id);
            if (log == null)
                return Json(new { error = 1 });

            _logger.DeleteLog(log);

            return Json(new { success = 1 });
        }

        [HttpPost]
        public IActionResult DeleteSelected(ICollection<int> selectedIds)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSystemLog))
                return HttpUnauthorized();

            if (selectedIds != null)
            {
                var logItems = _logger.GetLogByIds(selectedIds.ToArray());
                foreach (var logItem in logItems)
                    _logger.DeleteLog(logItem);
            }

            return Json(new { success = 1 });
        }
    }
}

Urs.Shop/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using Urs.Admin.Models.Common;
using Urs.Admin.Models.Coupons;
using Urs.Admin.Models.Users;
using Urs.Admin.Models.ShoppingCart;
using Urs.Core;
using Urs.Data.Domain.Common;
using Urs.Data.Domain.Users;
using Urs.Data.Domain.Orders;
using Urs.Data.Domain.Payments;
using Urs.Data.Domain.Shipping;
using Urs.Data.Domain.Configuration;
using Urs.Services;
using Urs.Services.Authentication.External;
using Urs.Services.Stores;
using Urs.Services.Common;
using Urs.Services.Users;
using Urs.Services.Directory;
using Urs.Services.ExportImport;
using Urs.Services.Localization;
using Urs.Services.Logging;
using Urs.Services.Media;
using Urs.Services.Orders;
using Urs.Services.Security;
using Urs.Framework;
using Urs.Framework.Controllers;
using Urs.Framework.Extensions;
using Urs.Framework.Kendoui;
using Urs.Framework.Mvc;
using Urs.Web.Infrastructure;
using Urs.Admin.Models.Common;

namespace Urs.Admin.Controllers
{
    [AdminAuthorize]
    public partial class UserController : BaseAdminController
    {
        #region Fields

        private readonly IUserService _userService;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly IUserRegistrationService _userRegistrationService;
        private readonly IUserReportService _userReportService;
        private readonly ILocalizationService _localizationService;
        private readonly RewardPointsSettings _rewardPointsSettings;
        private readonly IAddressService _addressService;
        private readonly UserSettings _userSettings;
        private readonly IWorkContext _workContext;
        private readonly IOrderService _orderService;
        private readonly IExportManager _exportManager;
        private readonly IGoodsSpecFormatter _goodsSpecFormatter;
        private readonly IActivityLogService _activityLogService;
        private readonly IPriceCalculationService _priceCalculationService;
        private readonly IPermissionService _permissionService;
        private readonly AdminAreaSettings _adminAreaSettings;
        private readonly IOpenAuthenticationService _openAuthenticationService;
        private readonly AddressSettings _addressSettings;
        private readonly IAreaService _areaService;
        private readonly IPictureService _pictureService;
        #endregion

        #region Constructors

        public UserController(IUserService userService,
            IShoppingCartService shoppingCartService,
            IUserRegistrationService userRegistrationService,
            IUserReportService userReportService,
            ILocalizationService localizationService,
             RewardPointsSettings rewardPointsSettings,
            IAddressService addressService,
            UserSettings userSettings,
            IWorkContext workContext,
            IOrderService orderService, IExportManager exportManager,
            IGoodsSpecFormatter goodsSpecFormatter,
            IActivityLogService activityLogService,
            IPriceCalculationService priceCalculationService,
            IPermissionService permissionService, AdminAreaSettings adminAreaSettings,
            IOpenAuthenticationService openAuthenticationService,
            AddressSettings addressSettings,
            IAreaService areaService,
            IPictureService pictureService)
        {
            this._userService = userService;
            this._userRegistrationService = userRegistrationService;
            this._shoppingCartService = shoppingCartService;
            this._userReportService = userReportService;
            this._localizationService = localizationService;
            this._rewardPointsSettings = rewardPointsSettings;
            this._goodsSpecFormatter = goodsSpecFormatter;
            this._addressService = addressService;
            this._userSettings = userSettings;
            this._workContext = workContext;
            this._orderService = orderService;
            this._exportManager = exportManager;
            this._activityLogService = activityLogService;
            this._priceCalculationService = priceCalculationService;
            this._permissionService = permissionService;
            this._adminAreaSettings = adminAreaSettings;
            this._openAuthenticationService = openAuthenticationService;
            this._addressSettings = addressSettings;
            this._areaService = areaService;
            this._pictureService = pictureService;
        }

        #endregion

        #region Utilities

        [NonAction]
        protected string GetSystemRolesNames(IList<UserRole> userRoles, string separator = ",")
        {
            var sb = new StringBuilder();
            for (int i = 0; i < userRoles.Count; i++)
            {
                sb.Append(userRoles[i].Name);
                if (i != userRoles.Count - 1)
                {
                    sb.Append(separator);
                    sb.Append(" ");
                }
            }
            return sb.ToString();
        }

        [NonAction]
        protected IList<RegisteredReportLineModel> GetReportRegisteredUsersModel()
        {
            var report = new List<RegisteredReportLineModel>();
            report.Add(new RegisteredReportLineModel()
            {
                Period = _localizationService.GetResource("Admin.Users.Reports.RegisteredUsers.Fields.Period.7days"),
                Users = _userReportService.GetRegisteredUsersReport(7)
            });

            report.Add(new RegisteredReportLineModel()
            {
                Period = _localizationService.GetResource("Admin.Users.Reports.RegisteredUsers.Fields.Period.14days"),
                Users = _userReportService.GetRegisteredUsersReport(14)
            });
            report.Add(new RegisteredReportLineModel()
            {
                Period = _localizationService.GetResource("Admin.Users.Reports.RegisteredUsers.Fields.Period.month"),
                Users = _userReportService.GetRegisteredUsersReport(30)
            });
            report.Add(new RegisteredReportLineModel()
            {
                Period = _localizationService.GetResource("Admin.Users.Reports.RegisteredUsers.Fields.Period.year"),
                Users = _userReportService.GetRegisteredUsersReport(365)
            });

            return report;
        }

        [NonAction]
        protected IList<UserModel.AssociatedExternalAuthModel> GetAssociatedExternalAuthRecords(User user)
        {
            if (user == null)
                throw new ArgumentNullException("user");

            var result = new List<UserModel.AssociatedExternalAuthModel>();
            foreach (var record in _openAuthenticationService.GetExternalIdentifiersFor(user))
            {
                var method = _openAuthenticationService.LoadExternalAuthenticationMethodBySystemName(record.ProviderSystemName);
                if (method == null)
                    continue;

                result.Add(new UserModel.AssociatedExternalAuthModel()
                {
                    Id = record.Id,
                    Name = record.Name,
                    OpenId = record.OpenId,
                    AvatarUrl = record.AvatarUrl,
                    AuthMethodName = method.PluginDescriptor.FriendlyName
                });
            }

            return result;
        }

        private string GetInviteCode(User user)
        {
            if (user == null)
                return "";
            if (user.AffiliateId == null)
                return "";
            if (user.AffiliateId.Value == 0)
                return "";

            var entity = _userService.GetUserById(user.AffiliateId.Value);
            if (entity == null) return "";

            return entity.GetFullName();
        }
        [NonAction]
        protected UserModel PrepareUserModelForList(User user, bool prepareAvatar)
        {
            var model = new UserModel()
            {
                Id = user.Id,
                Email = user.Email,
                PhoneNumber = user.PhoneNumber,
                FullName = user.GetFullName(),
                SystemRoleNames = GetSystemRolesNames(user.UserRoles.ToList()),
                LastIpAddress = user.LastIpAddress,
                Active = user.Active,
                Approved = user.Approved,
                InvitedCode = GetInviteCode(user),
                CreateTime = user.CreateTime,
                LastActivityDate = user.LastActivityTime,
                AdminComment = user.AdminComment,
                Nickname = user.Nickname
            };

            if (prepareAvatar)
            {
                model.AvatarPictureUrl = _pictureService.GetPictureUrl(user.AvatarPictureId, 100);
            }
            return model;
        }

        [NonAction]
        protected string ValidateRoles(IList<UserRole> userRoles)
        {
            if (userRoles == null)
                throw new ArgumentNullException("userRoles");

            //ensure a user is not added to both 'Guests' and 'Registered' user roles
            //ensure that a user is in at least one required role ('Guests' and 'Registered')
            bool isInGuestsRole = userRoles
                .Where(cr => cr.SystemName == SystemRoleNames.Guests)
                .FirstOrDefault() != null;
            bool isInRegisteredRole =
                userRoles
                .Where(cr => cr.SystemName == SystemRoleNames.Registered)
                .FirstOrDefault() != null;
            if (isInGuestsRole && isInRegisteredRole)
                return "The user cannot be in both 'Guests' and 'Registered' user roles";
            if (!isInGuestsRole && !isInRegisteredRole)
                return "Add the user to 'Guests' or 'Registered' user role";

            //no errors
            return "";
        }

Urs.Shop/Areas/Admin/Views/Log/List.cshtml
@model LogListModel

<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <button class="layui-btn  layui-btn-normal layuiadmin-btn-tags" data-type="add">添加</button>
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label">内容</label>
                    <div class="layui-input-inline">
                        <input class="layui-input" name="Message" id="Message" placeholder="请输入内容" autocomplete="off">
                    </div>
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label">类型</label>
                    <div class="layui-input-inline">
                        <u-select asp-for="LogLevelId" asp-items="Model.AvailableLogLevels" />
                    </div>
                </div>
                <div class="layui-inline">
                    <button class="layui-btn" lay-submit lay-filter="LAY-app-contlist-search">搜索</button>
                </div>
            </div>
        </div>
        <div class="layui-card-body">
            <table id="LAY-topic-list" lay-filter="LAY-topic-list"></table>
            <script type="text/html" id="layuiadmin-app-cont-tagsbar">
                <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="layui-icon layui-icon-edit"></i>查看</a>
            </script>
        </div>
    </div>
</div>

<script>

    layui.use(['index','table'], function () {
        var index = layer.load(2, { shade: false });
        var table = layui.table;
        //分类管理
        table.render({
            elem: '#LAY-topic-list'
            , url: '@Html.Raw(Url.Action("LogList", "Log"))' //模拟接口
            ,method:'post'
            , page: true //开启分页
            , even: true
            , limit: 15
            , limits: [15,30,50,100]
            , cols: [[
                { type: 'numbers', fixed: 'left' }
                , { field: 'Id', width: 100, title: 'ID' }
                , { field: 'LogLevel', title: '类型', width:100 }
                , { field: 'ShortMessage', title: '简介', minWidth: 150 }
                , { field: 'FullMessage', title: '内容', minWidth: 250 }
                , { field: 'CreateTime', title: '创建时间', width: 150 }
                , { title: '操作', width: 150, align: 'center', fixed: 'right', toolbar: '#layuiadmin-app-cont-tagsbar' }
            ]]
            , id: 'testReload'
            , text: { none: '一条数据也没有^_^' }
            , done: function () {
                layer.close(index);
            }
        });

        //监听搜索
        layui.form.on('submit(LAY-app-contlist-search)', function (data) {
            var field = data.field;
            //执行重载
            table.reload('testReload', {
                page: {   curr: 1   }
               , where: field
            }, 'data');
        });

        //监听工具条
        table.on('tool(LAY-topic-list)', function (obj) {
            var data = obj.data;
           if (obj.event === 'edit') {
                var tr = $(obj.tr);
                var index = layer.open({
                    title: '编辑'
                    , type: 2
                    , shade: 0.2
                    , maxmin: true
                    , shadeClose: true
                    , area: ['100%', '100%']
                    , content: '@Url.Action("View")?id=' + data.Id
                });
                $(window).on("resize", function () {
                    layer.full(index);
                });
                return false;
            }
        });

        var $ = layui.$, active = { }
        $('.layui-btn.layuiadmin-btn-tags').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
    });
</script>

Urs.Shop/Areas/Admin/Views/Log/View.cshtml
@model LogModel

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-body">
                    <div class="layui-form" wid200>
                        <div class="layui-form-item">
                            <div class="layui-inline">
                                <u-label asp-for="LogLevel" />
                                <div class="layui-form-mid layui-word-aux">
                                    @Model.LogLevel
                                </div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-inline">
                                <u-label asp-for="ShortMessage" />
                                <div class="layui-form-mid layui-word-aux">
                                    @Model.ShortMessage
                                </div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-inline">
                                <u-label asp-for="FullMessage" />
                                <div class="layui-form-mid">
                                    @Model.FullMessage
                                </div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-inline">
                                <u-label asp-for="IpAddress" />
                                <div class="layui-form-mid layui-word-aux">
                                   @Model.IpAddress
                                </div>
                            </div>
                        </div>
                        @if (Model.UserId.HasValue)
                        {
                            <div class="layui-form-item">
                                <div class="layui-inline">
                                    <u-label asp-for="UserId" />
                                    <div class="layui-form-mid layui-word-aux">
                                        @Html.ActionLink(!String.IsNullOrEmpty(Model.UserEmail) ? Model.UserEmail : T("Admin.Users.Guest").Text, "Edit", "User", new { id = Model.UserId }, new { })
                                    </div>
                                </div>
                            </div>
                        }
                        <div class="layui-form-item">
                            <div class="layui-inline">
                                <u-label asp-for="PageUrl" />
                                <div class="layui-form-mid layui-word-aux">
                                    @Model.PageUrl
                                </div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-inline">
                                <u-label asp-for="ReferrerUrl" />
                                <div class="layui-form-mid layui-word-aux">
                                    @Model.ReferrerUrl
                                </div>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-inline">
                                <u-label asp-for="CreateTime" />
                                <div class="layui-form-mid layui-word-aux">
                                    @Model.CreateTime
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    layui.use(['index']);
</script>